#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import argparse
import logging
import sys

import requests_cache

if __name__ == "__main__":

    common.configure_logging(logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-i', dest='read_from_standard_input', action='store_true',
        help="Read usernames / user ids from standard input as JSON")
    parser.add_argument(
        '-u', dest='username', action='store',
        help="Facebook username or user id, e.g. 'zuck' or '4' "
             "for Mark Zuckerberg")
    args = parser.parse_args()

    if not args.username and not args.read_from_standard_input:
        parser.print_help(file=sys.stderr)
        sys.exit(1)

    # Enable caching (2 hrs) to avoid hitting Facebook too much
    requests_cache.install_cache(expire_after=7200)

    fb_fetcher = create_production_fetcher()

    ids = []
    if args.read_from_standard_input:

        friend_list = common.load_json_from_fd(sys.stdin)
        if not friend_list:
            logging.error("No user ids passed on stdin")
            sys.exit(1)

        if type(friend_list) == dict:
            ids = friend_list.keys
        else:
            ids = friend_list

    else:

        ids.append(args.username)

    infos = fb_fetcher.fetch_user_infos(ids)

    print(common.prettify(infos))
