#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import sys

if __name__ == "__main__":

    config = common.configure(caching_secs_override=-1)
    if not config:
        sys.exit(1)

    fb_fetcher = create_production_fetcher(config)

    last_active_times = fb_fetcher.fetch_last_active_times()
    print(common.prettify(last_active_times))
