#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import logging
import sys
from collections import OrderedDict

import requests_cache

if __name__ == "__main__":

    common.configure_logging(logging.INFO)

    # Enable caching (2 hrs) to avoid hitting Facebook too much
    requests_cache.install_cache(expire_after=7200)

    fb_fetcher = create_production_fetcher()

    articles = common.load_json_from_fd(sys.stdin)

    if not articles:
        logging.error("No article ids passed on stdin")
        sys.exit(1)

    if type(articles) != dict and type(articles) != OrderedDict:
        logging.error("Articles have to be passed as a dictionary")
        sys.exit(1)

    reactions = fb_fetcher.fetch_reactions_per_user_for_articles(articles)

    print(common.prettify(reactions))
