#!/usr/bin/env python3

from core import common
from core.downloader import Downloader
from core.facebook_fetcher import FacebookFetcher

import logging

if __name__ == "__main__":

    common.configure_logging(logging.INFO)
    config = common.load_config()
    downloader = Downloader()
    fbFetcher = FacebookFetcher(downloader, config)

    last_active_times = fbFetcher.fetch_last_active_times()
    print(common.prettify(last_active_times))