#!/usr/bin/env python3

from core import common
from core.downloader import Downloader
from core.facebook_fetcher import FacebookFetcher

import json
import logging
import sys

import requests_cache

if __name__ == "__main__":

    # Enable caching (2 hrs) to avoid hitting Facebook too much
    requests_cache.install_cache(expire_after=7200)

    common.configure_logging(logging.WARN)
    config = common.load_config()
    downloader = Downloader()
    fbFetcher = FacebookFetcher(downloader, config)

    friend_list = {}
    try:
        friend_list = json.load(sys.stdin)

    except Exception as e:
        logging.error("Error parsing JSON from stdin, "
                    "got exception: '{0}'".format(e))

    if not friend_list:
        logging.error("No user ids passed on stdin")
        sys.exit(1)

    infos = fbFetcher.fetch_user_infos(friend_list.keys())

    print(common.prettify(infos))
