#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import json
import logging
import sys

import requests_cache

if __name__ == "__main__":

    common.configure_logging(logging.INFO)

    # Enable caching (2 hrs) to avoid hitting Facebook too much
    requests_cache.install_cache(expire_after=7200)

    fb_fetcher = create_production_fetcher()

    friend_list = common.load_json_from_fd(sys.stdin)

    if not friend_list:
        logging.error("No user ids passed on stdin")
        sys.exit(1)

    ids = []
    if type(friend_list) == dict:
        ids = friend_list.keys
    else:
        ids = friend_list

    infos = fb_fetcher.fetch_user_infos(ids)

    print(common.prettify(infos))
