#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import argparse
import logging
import sys
from collections import OrderedDict

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-e', dest='exclude_non_users', action='store_true',
        help="Exclude non users (e.g. Pages)")
    args = parser.parse_args()

    config = common.configure()
    if not config:
        sys.exit(1)

    fb_fetcher = create_production_fetcher(config)

    articles = common.load_json_from_fd(sys.stdin)

    if not articles:
        logging.error("No posts ids passed on stdin")
        sys.exit(1)

    if type(articles) != list:
        logging.error(
            "Posts have to be passed as a list of dictionaries containing "
            "the key post_id for every post.")
        sys.exit(1)

    reactions = fb_fetcher.fetch_reactions_per_user_for_articles(
        articles, args.exclude_non_users)

    print(common.prettify(reactions))
