#!/usr/bin/env python3

from core import common
from core.facebook_fetcher import create_production_fetcher

import logging
import sys

if __name__ == "__main__":

    config = common.configure()
    if not config:
        sys.exit(1)

    fb_fetcher = create_production_fetcher(config)

    friend_list = fb_fetcher.fetch_user_friend_list()

    logging.info("Found {0} friend(s)".format(len(friend_list)))

    print(common.prettify(friend_list))
