#!/usr/bin/env python3

from core import common
from core import model

import argparse
import logging
import sys

if __name__ == "__main__":

    common.configure_logging(logging.WARN)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-u', dest='user_infos_filepath', action='store',
        help="JSON file containing a mapping from user ids to names")
    parser.add_argument('-d', dest='denormalize', action='store_true')
    args = parser.parse_args()

    if not args.user_infos_filepath:
        parser.print_help()
        sys.exit(1)

    user_infos = common.load_json_from_file(args.user_infos_filepath)

    last_active_times = common.load_json_from_fd(sys.stdin)

    if not last_active_times:
        logging.error("No times passed on stdin")
        sys.exit(1)

    parsed = model.process_data(
        last_active_times, user_infos, True, args.denormalize)

    print(common.prettify(parsed))
