#! /bin/bash

where_am_i="${0%/*}"

# Enforce PEP8 coding conventions
pycodestyle --show-source \
  --filename=*.py,fetch*,poll*,process*,update* \
  --exclude ".git,__pycache__,tools" "${where_am_i}"

nosetests --with-doctest
