#! /bin/bash

where_am_i="${0%/*}"

# Enforce PEP8 coding conventions
pycodestyle --show-source \
  --filename=*.py,fetch*,poll*,process*,update* \
  --exclude ".git,__pycache__,tools" "${where_am_i}"

nosetests --with-doctest

# Only run bash tests if jq is installed since
# jq is not a requirement of the project
which jq >/dev/null && {
  ${where_am_i}/tests/denormalize-test
}