#!/usr/bin/env python3

from core import common
from core import model

import argparse
import logging
import sys

if __name__ == "__main__":

    common.configure_logging(logging.WARN)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-d', dest='database_path', action='store',
        help="Destination database to create or update")
    args = parser.parse_args()

    if not args.database_path:
        parser.print_help(file=sys.stderr)
        sys.exit(1)

    data = common.load_json_from_fd(sys.stdin)
    if not data:
        logging.error("No data passed on stdin")
        sys.exit(1)

    model.save_to_db(data, args.database_path)
