#! /bin/bash

set -u
set -e

where_am_i="${0%/*}"

input_file_dup=$(mktemp)
user_infos_file=$(mktemp)

# Only deal with standard input
cat - > "${input_file_dup}"

cat "${input_file_dup}" | ${where_am_i}/../fetch-user-infos $@ > "${user_infos_file}"

# Combine the two JSON files
jq -s '.[0] * .[1]' "${user_infos_file}" "${input_file_dup}"

rm "${input_file_dup}"
rm "${user_infos_file}"
